
// ********RoostGPT********
/*
Test generated by RoostGPT for test java_testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=updateSongFavouritesCount_b3fb26e6c7
ROOST_METHOD_SIG_HASH=updateSongFavouritesCount_318e57045a


Scenario 1: Update Favourites Count for Valid Song ID with Increment

Details:
  TestName: updateFavouritesCountValidIncrement
  Description: Test the behavior of updateSongFavouritesCount when a valid song ID is provided, and the favourites count should increment.

Execution:
  Arrange: Use a mock MongoTemplate (db) to simulate a valid Song instance already present in the database with a given favourites count.
  Act: Pass the valid song ID and `shouldDecrement` as `false` to the method `updateSongFavouritesCount`.
  Assert: Ensure that the favourite count is incremented by 1 and the returned `DbQueryStatus` object contains status OK.

Validation:
  Verify that the method correctly increments the favourites count of a song and returns a success status when a valid song ID is provided. This test is significant to confirm that the method handles positive scenarios as expected.

*/

// ********RoostGPT********

package com.csc301.songmicroservice;

import com.mongodb.client.result.DeleteResult;
import org.bson.types.ObjectId;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.data.mongodb.core.MongoTemplate;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

public class SongDalImplUpdateSongFavouritesCountTest {

	@Mock
	private MongoTemplate mockMongoTemplate;

	private SongDalImpl songDalImpl;

	@BeforeEach
	public void setUp() {
		MockitoAnnotations.openMocks(this);
		songDalImpl = new SongDalImpl(mockMongoTemplate);
	}

	@Test
	@Tag("valid")
	public void updateFavouritesCountValidIncrement() {
		// Arrange
		String validSongId = "507f1f77bcf86cd799439011"; // Dummy ObjectId
		Song mockSong = new Song("Test Song", "Test Artist", "Test Album");
		mockSong.setSongAmountFavourites(10L);
		when(mockMongoTemplate.findById(new ObjectId(validSongId), Song.class)).thenReturn(mockSong);
		when(mockMongoTemplate.save(mockSong)).thenReturn(mockSong);
		// Act
		DbQueryStatus result = songDalImpl.updateSongFavouritesCount(validSongId, false);
		// Assert
		assertEquals(songDalImpl.OK, result.getdbQueryExecResult());
		assertEquals(11L, mockSong.getSongAmountFavourites());
		verify(mockMongoTemplate).findById(new ObjectId(validSongId), Song.class);
		verify(mockMongoTemplate).save(mockSong);
	}

	@Test
	@Tag("valid")
	public void updateFavouritesCountValidDecrement() {
		// Arrange
		String validSongId = "507f1f77bcf86cd799439011"; // Dummy ObjectId
		Song mockSong = new Song("Test Song", "Test Artist", "Test Album");
		mockSong.setSongAmountFavourites(10L);
		when(mockMongoTemplate.findById(new ObjectId(validSongId), Song.class)).thenReturn(mockSong);
		when(mockMongoTemplate.save(mockSong)).thenReturn(mockSong);
		// Act
		DbQueryStatus result = songDalImpl.updateSongFavouritesCount(validSongId, true);
		// Assert
		assertEquals(songDalImpl.OK, result.getdbQueryExecResult());
		assertEquals(9L, mockSong.getSongAmountFavourites());
		verify(mockMongoTemplate).findById(new ObjectId(validSongId), Song.class);
		verify(mockMongoTemplate).save(mockSong);
	}

	@Test
	@Tag("invalid")
	public void updateFavouritesCountInvalidSongId() {
		// Arrange
		String invalidSongId = "invalidObjectId"; // Invalid ObjectId format
		// Act
		DbQueryStatus result = songDalImpl.updateSongFavouritesCount(invalidSongId, true);
		// Assert
		assertEquals(songDalImpl.ERR, result.getdbQueryExecResult());
		assertNull(result.getData());
		verify(mockMongoTemplate, never()).findById(any(ObjectId.class), any());
		verify(mockMongoTemplate, never()).save(any());
	}

	@Test
	@Tag("invalid")
	public void updateFavouritesCountSongNotFound() {
		// Arrange
		String validSongId = "507f1f77bcf86cd799439011"; // Dummy ObjectId
		when(mockMongoTemplate.findById(new ObjectId(validSongId), Song.class)).thenReturn(null);
		// Act
		DbQueryStatus result = songDalImpl.updateSongFavouritesCount(validSongId, false);
		// Assert
		assertEquals(songDalImpl.ERR404, result.getdbQueryExecResult());
		assertNull(result.getData());
		verify(mockMongoTemplate).findById(new ObjectId(validSongId), Song.class);
		verify(mockMongoTemplate, never()).save(any());
	}

	@Test
	@Tag("boundary")
	public void updateFavouritesCountBoundaryCaseZeroDecrement() {
		// Arrange
		String validSongId = "507f1f77bcf86cd799439011"; // Dummy ObjectId
		Song mockSong = new Song("Test Song", "Test Artist", "Test Album");
		mockSong.setSongAmountFavourites(0L); // Boundary case
		when(mockMongoTemplate.findById(new ObjectId(validSongId), Song.class)).thenReturn(mockSong);
		when(mockMongoTemplate.save(mockSong)).thenReturn(mockSong);
		// Act
		DbQueryStatus result = songDalImpl.updateSongFavouritesCount(validSongId, true);
		// Assert
		assertEquals(songDalImpl.OK, result.getdbQueryExecResult());
		assertEquals(-1L, mockSong.getSongAmountFavourites());
		verify(mockMongoTemplate).findById(new ObjectId(validSongId), Song.class);
		verify(mockMongoTemplate).save(mockSong);
	}

}